import { CHANGE_TAB, RESET_SELECTED_TAB } from '../actions/tabBar';
import { SELECT_SHOW } from '../actions/showsList';

export default tour = (state = initialState, action) => {
  switch (action.type) {
    case CHANGE_TAB:
      return {
        ...state,
        selectedTab: action.nextTab
      }
    case RESET_SELECTED_TAB:
      return {
        ...state,
        selectedTab: "details"
      }
    case SELECT_SHOW:
      return {
        ...state,
        selectedShowID: action.selectedShowID
      }
    default:
      return state;
  }
}

const initialState = {
  selectedTab: "details",
  selectedShowID: -1,
  shows: [
    {
      "id": 0,
      "yyyymmdd": "2016-06-22",
      "slashDate": "6/22",
      "niceDate": "June 22",
      "city": "Saint Paul",
      "state": "MN",
      "venue": "Xcel Energy Center",
      "venueID": 0,
      "cotID": 18055
    },
    {
      "id": 1,
      "yyyymmdd": "2016-06-24",
      "slashDate": "6/24",
      "niceDate": "June 24",
      "city": "Chicago",
      "state": "IL",
      "venue": "Wrigley Field",
      "venueID": 1,
      "cotID": 18032
    },
    {
      "id": 2,
      "yyyymmdd": "2016-06-25",
      "slashDate": "6/25",
      "niceDate": "June 25",
      "city": "Chicago",
      "state": "IL",
      "venue": "Wrigley Field",
      "venueID": 1,
      "cotID": 18033
    },
    {
      "id": 3,
      "yyyymmdd": "2016-06-26",
      "slashDate": "6/26",
      "niceDate": "June 26",
      "city": "Noblesville",
      "state": "IN",
      "venue": "Klipsch Music Center",
      "venueID": 2,
      "cotID": 18044
    },
    {
      "id": 4,
      "yyyymmdd": "2016-06-28",
      "slashDate": "6/28",
      "niceDate": "June 28",
      "city": "Philadelphia",
      "state": "PA",
      "venue": "The Mann",
      "venueID": 3,
      "cotID": 18003,
      "cotVenue": "the-mann-center-for-the-performing-arts"
    },
    {
      "id": 5,
      "yyyymmdd": "2016-06-29",
      "slashDate": "6/29",
      "niceDate": "June 29",
      "city": "Philadelphia",
      "state": "PA",
      "venue": "The Mann",
      "venueID": 3,
      "cotID": 18031,
      "cotVenue": "the-mann-center-for-the-performing-arts"
    },
    {
      "id": 6,
      "yyyymmdd": "2016-07-01",
      "slashDate": "7/1",
      "niceDate": "July 1",
      "city": "Saratoga Springs",
      "state": "NY",
      "venue": "SPAC",
      "venueID": 4,
      "cotID": 18028,
      "cotVenue": "saratoga-performing-arts-center"
    },
    {
      "id": 7,
      "yyyymmdd": "2016-07-02",
      "slashDate": "7/2",
      "niceDate": "July 2",
      "city": "Saratoga Springs",
      "state": "NY",
      "venue": "SPAC",
      "venueID": 4,
      "cotID": 18029,
      "cotVenue": "saratoga-performing-arts-center"
    },
    {
      "id": 8,
      "yyyymmdd": "2016-07-03",
      "slashDate": "7/3",
      "niceDate": "July 3",
      "city": "Saratoga Springs",
      "state": "NY",
      "venue": "SPAC",
      "venueID": 4,
      "cotID": 18030,
      "cotVenue": "saratoga-performing-arts-center"
    },
    {
      "id": 9,
      "yyyymmdd": "2016-07-06",
      "slashDate": "7/6",
      "niceDate": "July 6",
      "city": "Portland",
      "state": "ME",
      "venue": "Cross Insurance Arena",
      "venueID": 5,
      "cotID": 18041
    },
    {
      "id": 10,
      "yyyymmdd": "2016-07-08",
      "slashDate": "7/8",
      "niceDate": "July 8",
      "city": "Mansfield",
      "state": "MA",
      "venue": "Xfinity Center",
      "venueID": 6,
      "cotID": 18056,
      "cotVenue": "xfinity-center-formerly-comcast-center"
    },
    {
      "id": 11,
      "yyyymmdd": "2016-07-09",
      "slashDate": "7/9",
      "niceDate": "July 9",
      "city": "Hartford",
      "state": "CT",
      "venue": "Xfinity Theatre",
      "venueID": 7,
      "cotID": 18034
    },
    {
      "id": 12,
      "yyyymmdd": "2016-07-10",
      "slashDate": "7/10",
      "niceDate": "July 10",
      "city": "Syracuse",
      "state": "NY",
      "venue": "Lakeview Amphitheater",
      "venueID": 8,
      "cotID": 17997
    },
    {
      "id": 13,
      "yyyymmdd": "2016-07-15",
      "slashDate": "7/15",
      "niceDate": "July 15",
      "city": "George",
      "state": "WA",
      "venue": "The Gorge",
      "venueID": 9,
      "cotID": 18078,
      "cotVenue": "the-gorge-amphitheatre"
    },
    {
      "id": 14,
      "yyyymmdd": "2016-07-16",
      "slashDate": "7/16",
      "niceDate": "July 16",
      "city": "George",
      "state": "WA",
      "venue": "The Gorge",
      "venueID": 9,
      "cotID": 18079,
      "cotVenue": "the-gorge-amphitheatre"
    },
    {
      "id": 15,
      "yyyymmdd": "2016-07-18",
      "slashDate": "7/18",
      "niceDate": "July 18",
      "city": "San Francisco",
      "state": "CA",
      "venue": "Bill Graham Civic Auditorium",
      "venueID": 10,
      "cotID": 18045,
      "cotVenue": "bill-graham-civic-center-auditorium"
    },
    {
      "id": 16,
      "yyyymmdd": "2016-07-19",
      "slashDate": "7/19",
      "niceDate": "July 19",
      "city": "San Francisco",
      "state": "CA",
      "venue": "Bill Graham Civic Auditorium",
      "venueID": 10,
      "cotID": 18046,
      "cotVenue": "bill-graham-civic-center-auditorium"
    },
    {
      "id": 17,
      "yyyymmdd": "2016-07-20",
      "slashDate": "7/20",
      "niceDate": "July 20",
      "city": "San Francisco",
      "state": "CA",
      "venue": "Bill Graham Civic Auditorium",
      "venueID": 10,
      "cotID": 18047,
      "cotVenue": "bill-graham-civic-center-auditorium"
    },
    {
      "id": 18,
      "yyyymmdd": "2016-07-22",
      "slashDate": "7/22",
      "niceDate": "July 22",
      "city": "Inglewood",
      "state": "CA",
      "venue": "The Forum",
      "venueID": 11,
      "cotID": 18051
    },
    {
      "id": 19,
      "yyyymmdd": "2016-07-23",
      "slashDate": "7/23",
      "niceDate": "July 23",
      "city": "Chula Vista",
      "state": "CA",
      "venue": "Sleep Train Amphitheatre",
      "venueID": 12,
      "cotID": 18054
    },
    {
      "id": 20,
      "yyyymmdd": "2016-08-26",
      "slashDate": "8/26",
      "niceDate": "August 26",
      "city": "Arrington",
      "state": "VA",
      "venue": "Lockn' Festival",
      "venueID": 13,
      "cotID": 0
    },
    {
      "id": 21,
      "yyyymmdd": "2016-08-28",
      "slashDate": "8/28",
      "niceDate": "August 28",
      "city": "Arrington",
      "state": "VA",
      "venue": "Lockn' Festival",
      "venueID": 13,
      "cotID": 0
    },
    {
      "id": 22,
      "yyyymmdd": "2016-09-02",
      "slashDate": "9/2",
      "niceDate": "September 2",
      "city": "Commerce City",
      "state": "CO",
      "venue": "Dick's",
      "venueID": 14,
      "cotID": 18050,
      "cotVenue": "dick-s-sporting-goods-park"
    },
    {
      "id": 23,
      "yyyymmdd": "2016-09-03",
      "slashDate": "9/3",
      "niceDate": "September 3",
      "city": "Commerce City",
      "state": "CO",
      "venue": "Dick's",
      "venueID": 14,
      "cotID": 18048,
      "cotVenue": "dick-s-sporting-goods-park"
    },
    {
      "id": 24,
      "yyyymmdd": "2016-09-04",
      "slashDate": "9/4",
      "niceDate": "September 4",
      "city": "Commerce City",
      "state": "CO",
      "venue": "Dick's",
      "venueID": 14,
      "cotID": 18049,
      "cotVenue": "dick-s-sporting-goods-park"
    },
  ],
  venues: [
    {
      "id": 0,
      "venue": "Xcel Energy Center",
      "address": "199 W. Kellogg Blvd",
      "city": "St. Paul",
      "state": "MN",
      "zip": "55102",
      "latitude": 44.944808,
      "longitude": -93.101103,
      "phone": "(651) 726-8240",
      "capacity": "18,568",
      "showTime": "7:30pm",
      "doorTime": "6:30pm",
      "lotTime": "n/a",
      "timeZone": "CT",
      "photos": ["http://i.imgur.com/fExsDqE.jpg", "http://imgur.com/G0PJiKE.jpg"],
      "seatingChart": "http://i.imgur.com/mzlkCcS.png",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This place has good beer",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 1,
      "venue": "Wrigley Field",
      "address": "1060 W. Addison St",
      "city": "Chicago",
      "state": "IL",
      "zip": "60613",
      "latitude": 41.948462,
      "longitude": -87.655333,
      "phone": "(773) 404-2827",
      "capacity": "42,000",
      "showTime": "7:00pm",
      "doorTime": "5:00pm",
      "lotTime": "n/a",
      "timeZone": "CT",
      "photos": ["http://imgur.com/B1xzxTo.jpg", "http://imgur.com/4pNUV4L.jpg"],
      "seatingChart": "http://imgur.com/OOfO59J.jpg",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This place has good beer",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 2,
      "venue": "Klipsch Music Center",
      "address": "12880 E 146th St",
      "city": "Noblesville",
      "state": "IN",
      "phone": "(317) 776-8181",
      "zip": "46060",
      "latitude": 40.004989,
      "longitude": -85.930968,
      "capacity": "24,000",
      "showTime": "7:30pm",
      "doorTime": "6:00pm",
      "lotTime": "3:00pm",
      "timeZone": "CT",
      "photos": ["http://imgur.com/QCxAH0p.jpg", "http://imgur.com/KMfukij.jpg"],
      "seatingChart": "http://imgur.com/qPvOgjX.jpg",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This place has good beer",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 3,
      "venue": "Mann Center for the Performing Arts",
      "address": "5201 Parkside Ave",
      "city": "Philadelphia",
      "state": "PA",
      "phone": "(215) 546-7900",
      "zip": "19131",
      "latitude": 39.983317,
      "longitude": -75.222969,
      "capacity": "14,000",
      "showTime": "7:30pm",
      "doorTime": "6:00pm",
      "lotTime": "n/a",
      "timeZone": "ET",
      "photos": ["http://i.imgur.com/54CaQAd.jpg", "http://imgur.com/KKBu9kR.jpg", "http://imgur.com/ltq9LH3.jpg"],
      "seatingChart": "http://i.imgur.com/Kds4ZYB.png",
      "thingsToDo": [
        {
          "name": "Drink Good Beer",
          "category": "bar",
          "address": "264 S 16th St",
          "city": "Philadelphia",
          "state": "PA",
          "latitude": 39.947688,
          "longitude": -75.168094,
          "url": "http://www.phillytapfinder.com/",
          "price": 2,
          "proTip": "Don't skip Tired Hands.",
          "description": "Philadelphia is one of the best beer cities in the country. Some of my favorite drinking spots are Monk's Cafe (ask to see their bottle list), POPE, Good Dog, Strangelove's, Memphis Tap Room, and City Tap House. Outside of the city, Tired Hands Brewing Company in Ardmore is a can't miss.",
        },
        {
          "name": "Get to the lot early",
          "category": "outdoors",
          "address": "5201 Parkside Ave",
          "city": "Philadelphia",
          "state": "PA",
          "latitude": 39.983303,
          "longitude": -75.222905,
          "url": "http://manncenter.org/",
          "price": 1,
          "proTip": "Sunscreen is sexy.",
          "description": "In past years, the lots have opened at 10am for Phish. At the Mann, the \"lot\" is actually Fairmont Park. There is plenty of grass and shade and open space to enjoy pre-show.",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 4,
      "venue": "Saratoga Performing Arts Center",
      "address": "108 Avenue of the Pines",
      "city": "Saratoga Springs",
      "state": "NY",
      "phone": "(518) 584-9330",
      "zip": "12866",
      "latitude": 43.055411,
      "longitude": -73.805906,
      "capacity": "25,100",
      "showTime": "7:30pm",
      "doorTime": "6:00pm",
      "lotTime": "4:30pm",
      "timeZone": "ET",
      "photos": ["http://i.imgur.com/34ecdbu.jpg", "http://i.imgur.com/CMaeSGu.jpg", "http://i.imgur.com/QLKWPpE.jpg", "http://i.imgur.com/uMgj9HN.jpg"],
      "seatingChart": "http://i.imgur.com/NaAVf2C.gif",
      "thingsToDo": [
        {
          "name": "Saratoga Spa State Park",
          "category": "outdoors",
          "address": "19 Roosevelt Drive",
          "city": "Saratoga Springs,
          "state": "NY",
          "latitude": 43.055291,
          "longitude": -73.800897,
          "url": "http://www.nysparks.com/parks/saratogaspa",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "SPAC is located in a gorgeous state park that is worth exploring during the day. You can find miles of hiking and biking trails, natural mineral water springs, a golf (and disc golf) course, museums, pools, stunning classical architecture and so much more.",
        },
        {
          "name": "Lake George",
          "category": "outdoors",
          "address": "123 Main St",
          "city": "Lake George",
          "state": "NY",
          "latitude": 43.436333,
          "longitude": -73.694565,
          "url": "http://www.visitlakegeorge.com/home",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Located a half hour north of Saratoga, Lake George is home to balloon rides, boat cruises, galleries, golf, historic sites, hiking, horseback riding, markets, museums, outlet shopping, scenic train rides, swimming, whitewater rafting, and much more.",
        },
        {
          "name": "Druthers Brewing Company",
          "category": "brewery",
          "address": "381 Broadway",
          "city": "Saratoga Springs",
          "state": "NY",
          "latitude": 43.080880,
          "longitude": -73.786025,
          "url": "http://www.druthersbrewing.com/",
          "price": 2,
          "proTip": "Try a pour of their gold-medal winning gose, \"The Dare\".",
          "description": "Druthers is a beautiful brewpub situated right on Broadway in downtown Saratoga. They feature a dozen of their own beers on tap, plus an eclectic food menu sourced from local ingredients to enjoy on their spacious outdoor patio.",
        },
      ],
    },
    {
      "id": 5,
      "venue": "Cross Insurance Arena",
      "address": "1 Civic Center Square",
      "city": "Portland",
      "state": "ME",
      "phone": "(207) 775-3458",
      "zip": "04101",
      "latitude": 43.655530,
      "longitude": -70.259223,
      "capacity": "6,733",
      "showTime": "7:30pm",
      "doorTime": "6:00pm",
      "lotTime": "n/a",
      "timeZone": "ET",
      "photos": ["http://i.imgur.com/tprCd6P.jpg", "http://i.imgur.com/hqPpI7e.jpg"],
      "seatingChart": "http://i.imgur.com/wBlQh40.gif",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This place has good beer",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 6,
      "venue": "Xfinity Center",
      "address": "855 South Main St",
      "city": "Mansfield",
      "state": "MA",
      "phone": "(508) 339-2331",
      "zip": "02048",
      "latitude": 41.992408,
      "longitude": -71.220240,
      "capacity": "19,900",
      "showTime": "7:00pm",
      "doorTime": "6:00pm",
      "lotTime": "3:00pm",
      "timeZone": "ET",
      "photos": ["http://i.imgur.com/zBCIULy.jpg", "http://i.imgur.com/a2cII90.jpg"],
      "seatingChart": "http://i.imgur.com/kp7oejD.gif",
      "thingsToDo": [
        {
          "name": "Trillium Brewing Compnay",
          "category": "brewery",
          "address": "110 Shawmut Road",
          "city": "Canton",
          "state": "MA",
          "latitude": 42.184426,
          "longitude": -71.152427,
          "url": "http://www.trilliumbrewing.com/",
          "price": 2,
          "proTip": "If you're going to buy just a few bottles, make sure that includes some of the double dry-hopped pale ales.",
          "description": "Located between the venue and Boston, Trillium is consistenly making some of the best hoppy beers in the country. ",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 7,
      "venue": "Xfinity Theatre",
      "address": "61 Savitt Way",
      "city": "Hartford",
      "state": "CT",
      "phone": "(860) 548-7370",
      "zip": "06120",
      "latitude": 41.779938,
      "longitude": -72.669191,
      "capacity": "30,000",
      "showTime": "7:30pm",
      "doorTime": "6:00pm",
      "lotTime": "4:30pm",
      "timeZone": "ET",
      "photos": ["http://i.imgur.com/eWHHx4Q.jpg", "http://i.imgur.com/fobgq6W.jpg"],
      "seatingChart": "http://i.imgur.com/tgm1Ai7.png",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This place has good beer",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 8,
      "venue": "Lakeview Amphitheater",
      "address": "490 Restoration Way",
      "city": "Syracuse",
      "state": "NY",
      "phone": "(315) 435-2121",
      "zip": "13209",
      "latitude": 43.089542,
      "longitude": -76.220359,
      "capacity": "17,500",
      "showTime": "7:30pm",
      "doorTime": "6:00pm",
      "lotTime": "4:30pm",
      "timeZone": "ET",
      "photos": ["http://i.imgur.com/WDUIQWQ.jpg", "http://i.imgur.com/MTsRL0T.jpg"],
      "seatingChart": "http://i.imgur.com/9yzujv2.jpg",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This place has good beer",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 9,
      "venue": "Gorge Amphitheatre",
      "address": "754 Silica Road NW",
      "city": "George",
      "state": "WA",
      "phone": "(509) 785-6262",
      "zip": "98848",
      "latitude": 47.101383,
      "longitude": -119.995803,
      "capacity": "20,000",
      "showTime": "7:30pm",
      "doorTime": "5:30pm",
      "lotTime": "2:00pm",
      "timeZone": "PT",
      "photos": ["http://i.imgur.com/yLwGaKp.png", "http://i.imgur.com/OncQDiN.jpg", "http://i.imgur.com/TmjpHcx.jpg", "http://i.imgur.com/XBjY01Z.jpg"],
      "seatingChart": "http://i.imgur.com/eN8sHWv.jpg",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This place has good beer",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 10,
      "venue": "Bill Graham Civic Auditorium",
      "address": "99 Grove St",
      "city": "San Francisco",
      "state": "CA",
      "phone": "(415) 864-0815",
      "zip": "94102",
      "latitude": 37.778025,
      "longitude": -122.417436,
      "capacity": "7,000",
      "showTime": "7:30pm",
      "doorTime": "6:00pm",
      "lotTime": "n/a",
      "timeZone": "PT",
      "photos": ["http://i.imgur.com/hCgnZQs.jpg", "http://i.imgur.com/NkoTwA4.jpg", "http://i.imgur.com/7eWtMis.jpg"],
      "seatingChart": "http://i.imgur.com/IxSSToE.gif",
      "thingsToDo": [
        {
          "name": "Cellarmaker Brewing Company",
          "category": "brewery",
          "address": "1150 Howard St",
          "city": "San Francisco",
          "state": "CA",
          "latitude": 37.777157,
          "longitude": -122.410722,
          "url": "http://www.cellarmakerbrewing.com/",
          "price": 2,
          "proTip": "Closed on Mondays.",
          "description": "One of the best breweries in the Bay Area just so happens to be walking distance from the venue! Bring in outside food to enjoy with your beer. Also be sure to check out City Beer Store a block away for a solid tap list and bottles both to-go and for in-house consumption.",
        },
        {
          "name": "Rye Project",
          "category": "restaurant",
          "address": "180 7th St",
          "city": "San Francisco",
          "state": "CA",
          "latitude": 37.778121,
          "longitude": -122.410090,
          "url": "http://www.ryeproject.com/",
          "price": 3,
          "proTip": "Bring your sandwich to Cellarmaker or City Beer Store!",
          "description": "This 'newish delicatessen' has some pretty stellar (albeit pricey) pastrami and corned beef sandwiches. They're only open during lunch hours (11am-3pm).",
        },
        {
          "name": "Golden Gate Disc Golf",
          "category": "activity",
          "address": "900 John F Kennedy Dr",
          "city": "San Francisco",
          "state": "CA",
          "latitude": 37.770954,
          "longitude": -122.486250,
          "url": "http://www.sfdiscgolf.org/contact",
          "price": 0,
          "proTip": "!",
          "description": "Well-maintained 18-hole disc golf course in beautiful Golden Gate Park. If you need to rent discs, check out Golden Gate Park Bike & Skate on Fulton St.",
        },
      ],
    },
    {
      "id": 11,
      "venue": "The Forum",
      "address": "3900 W. Manchester Blvd",
      "city": "Inglewood",
      "state": "CA",
      "phone": "(310) 330-7300",
      "zip": "90305",
      "latitude": 33.958229,
      "longitude": -118.341922,
      "capacity": "18,000",
      "showTime": "7:30pm",
      "doorTime": "6:30pm",
      "lotTime": "n/a",
      "timeZone": "PT",
      "photos": ["http://i.imgur.com/8lFQ3Bc.jpg", "http://i.imgur.com/IyrcGNn.jpg"],
      "seatingChart": "http://i.imgur.com/0L3P7GX.jpg",
      "thingsToDo": [
        {
          "name": "Bay Cities Italian Deli & Bakery",
          "category": "restaurant",
          "address": "1517 Lincoln Blvd",
          "city": "Santa Monica",
          "state": "CA",
          "latitude": 34.017985,
          "longitude": -118.489180,
          "url": "http://www.baycitiesitaliandeli.com/",
          "price": 1,
          "proTip": "Order the Godmother.",
          "description": "A classic Italian deli, perfect for grabbing a sandwich to go for the beach or lot. Lines can be long, but they move fast.",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 12,
      "venue": "Sleep Train Amphitheatre",
      "address": "2050 Entertainment Circle",
      "city": "Chula Vista",
      "state": "CA",
      "phone": "(619) 671-3500",
      "zip": "91911",
      "latitude": 32.588278,
      "longitude": -117.006046,
      "capacity": "20,500",
      "showTime": "7:00pm",
      "doorTime": "6:00pm",
      "lotTime": "n/a",
      "timeZone": "PT",
      "photos": ["http://i.imgur.com/jkpnFzX.jpg", "http://i.imgur.com/03M6zxi.jpg"],
      "seatingChart": "http://i.imgur.com/SnZBMc2.gif",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Pokem ipsum dolor sit amet Krokorok Drifblim Unown Calcium Cresselia quis nostrud exercitation. Ash Monferno Xatu Soda Pop Ledyba Honchkrow Trubbish. Earthquake Trapinch Palkia Bulbasaur Seadra Chingling Normal. Splash Solosis Dig Dusknoir Simisear Grumpig Seadra. Velit esse cillum dolore eu fugiat nulla pariatur Victreebel Pelipper Water Kricketot Blizzard Badge. ",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Bacon ipsum dolor amet prosciutto turkey chicken shank swine. Drumstick pork loin short loin strip steak t-bone ham kevin pastrami bacon. Fatback landjaeger andouille leberkas ground round pork picanha chuck flank turkey ham hock strip steak tongue. Alcatra flank biltong pork chop bresaola, shank swine beef ribs pig filet mignon pastrami landjaeger ground round hamburger t-bone. Swine cow biltong venison. Boudin pancetta swine porchetta.",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "And even if he's a lazy man, and the Dude was certainly that—quite possibly the laziest in Los Angeles County. I don't see any connection to Vietnam, Walter. He lives in North Hollywood on Radford, near the In-and-Out Burger.",
        },
      ],
    },
    {
      "id": 13,
      "venue": "Lockn' Festival",
      "address": "Oak Ridge Farm",
      "city": "Arrington",
      "state": "VA",
      "phone": "1-(800)-594-TIXX",
      "zip": "22922",
      "latitude": 37.254340,
      "longitude": -79.675751,
      "capacity": "40,000",
      "showTime": "n/a",
      "doorTime": "n/a",
      "lotTime": "n/a",
      "timeZone": "ET",
      "photos": ["http://i.imgur.com/phFSzZx.jpg", "http://i.imgur.com/06EqHHJ.jpg"],
      "seatingChart": "",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This place has good beer",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
    {
      "id": 14,
      "venue": "Dick's Sporting Goods Park",
      "address": "6000 Victory Way",
      "city": "Commerce City",
      "state": "CO",
      "phone": "(303) 727-3500",
      "zip": "80022",
      "latitude": 39.805711,
      "longitude": -104.891790,
      "capacity": "40,000",
      "showTime": "7:30pm",
      "doorTime": "6:00pm",
      "lotTime": "3:00pm",
      "timeZone": "MT",
      "photos": ["http://i.imgur.com/0uVkZ8a.jpg", "http://i.imgur.com/0uVkZ8a.jpg"],
      "seatingChart": "http://i.imgur.com/06EqHHJ.jpg",
      "thingsToDo": [
        {
          "name": "Sick Brewery",
          "category": "brewery",
          "address": "123 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This place has good beer",
        },
        {
          "name": "Sweet Park",
          "category": "outdoors",
          "address": "456 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "This is a park with trees",
        },
        {
          "name": "Food Co. Inc",
          "category": "restaurant",
          "address": "789 Main St",
          "city": "St. Paul",
          "state": "MN",
          "latitude": 44.944808,
          "longitude": -93.101103,
          "url": "http://www.gotablank.space",
          "price": 0,
          "proTip": "Don't forget to bring a towel!",
          "description": "Yummy eats",
        },
      ],
    },
  ],
};
